name: Python application deploy to Azure Functions

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
      
    - name: 'Set up Python 3.11'
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: 'Install dependencies'
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: <Your-Function-App-Name>
        package: .
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

    - name: 'Logout of Azure CLI'
      run: |
        az logout